/*eslint max-len: ["error", { "ignoreStrings": true }]*/

module.exports = {
  fullstack: "Unix, REST API, jQuery, JSON, TDD, Ruby, MongoDB, Babel, Angular, Javascript, HTML5, Git, Flux, HTML, UX, Node, Redux, AWS, React, Java, CSS, Python, Ember, PHP, Nodejs, SQL, Redux, Node, Webpack, Redux, CSS3, Django, Rails, Sass, NoSQL, MySQL, ES6, MVC, redis, Emberjs, Docker, Linux, Boostrap, Linux, Reactjs",
  web: "Unix, REST API, jQuery, JSON, TDD, Ruby, MongoDB, Babel, Angular, Javascript, HTML5, Git, Flux, HTML, UX, Node, Redux, AWS, React, Java, CSS, Python, Ember, PHP, Nodejs, SQL, Redux, Node, Webpack, Redux, CSS3, Django, Rails, Sass, NoSQL, MySQL, ES6, MVC, redis, Emberjs, Docker, Linux, Boostrap, Linux, Reactjs",
  frontend: "Node, Github, jQuery, Django, PHP, nodejs, JSX, NPM, JSON, Mongo, AngularJS, Jest, TDD, Backbone, HTML5, Mocha, API, D3, SASS, D3, Meteorjs, Webpack, NoSQL, HTML, CSS, Javascript, Ember, SQL, ES6, Python, MongoDB, HTTP, AJAX, CSS3, Redux, REST, Rails, grunt, SCRUM, MySQL, MVC, VueJS",
  backend: "Docker, SQS, TDD, Unix, SQL, NoSQL, Rails, RubyonRails, MongoDB, Java, AWS, C++, Cassandra, Node, DataStructures, Salesforce, Redis, API, S3, MVC, machinelearning, PostgreSQL, REST, iOS, Go, Ruby, EC2, Python, Git, Elixir, DynamoDB, Django, Hadoop, Go, Spark, PHP, Kafka, Agile, DynamoDB, Elixir",
  management: "Bottom-Line Focused, Business Analysis, Business Development, Contract Negotiation, Corporate Accountability, Corporate Strategizing, Customer Relations, Financial Management, Financial Strategies, Fiscal Accountability, Forecasting, Budgeting, Goal Setting, Business Planning, Growth Expansion, Human Resources Management, Judgement, Decision Making, Leader Vision, Influencing, Market Positioning, Operations Management, Organizational Development, Profit and Loss Management, Regulatory Reporting, Resources Management, Revenue Forecasting, Risk Management, Strategic Alliance Development, Venture Capital Financing",
  sales: "Account Management, Business Development, Channel Management, C-Level Presentations, Competitive Analysis, Consultative Selling, Contract Negotiation, Cross-Selling, Up-Selling, Customer Retention, Deal Negotiation, Closing, Lead Management, Market Research, Market Analysis, Marketing Management, Post Sales Support, Prospect Qualifying, Prospecting, Cold Calling, Relationship Management, RFP, RFI, Bid Preparation, Sales Cycle Management, Sales Forecasting, Sales Budgeting, Sales Management, Strategic Alliance Development, Territory Management, Product Development, Product Lifecycle",
  marketing: "Account Management, Business Development, Channel Management, C-Level Presentations, Competitive Analysis, Consultative Selling, Contract Negotiation, Cross-Selling, Up-Selling, Customer Retention, Deal Negotiation, Closing, Lead Management, Market Research, Market Analysis, Marketing Management, Post Sales Support, Prospect Qualifying, Prospecting, Cold Calling, Relationship Management, RFP, RFI, Bid Preparation, Sales Cycle Management, Sales Forecasting, Sales Budgeting, Sales Management, Strategic Alliance Development, Territory Management, Product Development, Product Lifecycle",
  accounting: "Accounting Systems and Controls, Auditing, Budgeting, Capital Acquisitions, Cash Flow Analysis, Corporate Reporting, Cost Accounting, Credit Management, Debt Management, Estate Planning, Financial Compliance, Financial Management, Financial Negotiations, Financial Planning, Financial Presentations, Financial Reporting, Financial Strategizing, General Accounting, Income Tax Planning, Internal Controls, Investment Strategies, Management Accounting, Payroll Management, Personal Financial Planning, Profit and Loss Management, Revenue Forecasting, Sales Forecasting, Tax Schedules, Remittances, Venture Capital",
  finance: "Accounting Systems and Controls, Auditing, Budgeting, Capital Acquisitions, Cash Flow Analysis, Corporate Reporting, Cost Accounting, Credit Management, Debt Management, Estate Planning, Financial Compliance, Financial Management, Financial Negotiations, Financial Planning, Financial Presentations, Financial Reporting, Financial Strategizing, General Accounting, Income Tax Planning, Internal Controls, Investment Strategies, Management Accounting, Payroll Management, Personal Financial Planning, Profit and Loss Management, Revenue Forecasting, Sales Forecasting, Tax Schedules, Remittances, Venture Capital",
  engineering: "Business Process Re-engineering, Components and Assemblies, Construction Management, Consultation and Project Conceptualization, Contract Negotiation, Data Collection and Analysis, Design Build, Structural Design, Design Methodologies, Design Verification Testing, Environmental Impact Study, Project Estimating, Fabricating Methodologies, Feasibility Study, Fluid Mechanics, Mechanical and Control Systems, Operations Management, Preventative Maintanence, Process Control, Process Methodologies, Project Management, Prototyping, Qualitative Analysis, Quantitative Analysis, Regulatory Compliance, Requirements, Technical Guidelines, Technical Specifications, Technical Writing, Tender Documentation and Contract",
  hr: "Benefits and Compensation, Collective Agreement, Conflict Resolution, Contract Negotiation, Employee Assistance and Wellness, Employer Value Proposition, Executive Development, Executive Sponsorship, Executive Influencing, Grievance and Arbitration, HR Policy Development and Execution, Human Resource Administration, Human Resource Systems, Industrial Relations, Payroll Administration, Performance Management, Job Analysis, Job Development, Lawsuit Settlement Assistance, Merger and Acquisition, Occupational Health and Safety, Organizational Development, Recruitment and Selection, Resources Planning, Resources Budgeting, Risk Management, Settlement Negotiation, Succession Planning, Talent Development, Talent Retention, Training and Development, Workers' Compensation Administration",
  it: "Business Analysis, Cloud Computing, Compliance and Security, Customization and Configuration, Data Localization, Data Management, Server Management, Database Management, Database Design, Disaster Recovery, MS SQL, Java Technology, Network Administration, Network Engineering, Open Source Technology, Product Lifecycle Development, Professional Service, Programming, Coding, Quality Assurance, Code Testing, Scalability, Product Extensions, Software Development, Software Installation, Software Upgrade, Software-as-is-Service, System Integration, Technology Stack, User Interface Design",
  manufacturing: "Accident Prevention, Assembly, Audit Control Procedures, Capacity Planning, Capacity Machinery Acquisition, CNC Machining, PLC Machining, Distribution Management, Facility Management, Forecasting, Budgeting, Inventory Management, ISO 9000 Compliance, Lean Manufacturing, Agile Manufacturing, Logistics, Materials Management, Plant Management, Preventative Maintanence, Machine Downtime, Process Improvement, Product Testing, Product Validation, Production Management, Production Methodologies, Production Scheduling, Profit and Loss Responsibility, Prototype Design, Purchasing, Procurement, Quality Assurance, Re-Tooling, Safety Documentation, Total Quality Management, Warehouse Management"
};
